# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=255, verbose_name='Context of the Quote')),
                ('date', models.DateField(verbose_name='Date of the Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('text', models.CharField(max_length=255, verbose_name='Text of the Quote')),
                ('quip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quips.Quip')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Speaker')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quips.Speaker'),
        ),
    ]
