# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quips.Quip",
            ),
        ),
    ]
