# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quips', '0002_auto_20160311_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='quip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
