# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quips', '0003_quip_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Clique')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='cliques',
            field=models.ManyToManyField(to='quips.Clique'),
        ),
    ]
