# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quips", "0005_quip_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="should_obfuscate",
            field=models.BooleanField(
                default=True, verbose_name="Should the displayed name be obfuscated"
            ),
        ),
    ]
