image: python:3.7

flake8:
  stage: test
  before_script:
    - pip install tox pipenv
  script: tox -eflake8

unit tests:
  stage: test
  before_script:
    - pip install tox pipenv codecov
  script:
    - tox -epy37
    - codecov

include:
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

