image: python:3.10

check requirements.txt:
  stage: test
  before_script:
    - pip install poetry
  script:
    - poetry export -f requirements.txt | diff requirements.txt -

flake8:
  stage: test
  before_script:
    - pip install tox poetry
  script: tox -eflake8

unit tests:
  stage: test
  before_script:
    - pip install tox poetry codecov
  script:
    - tox -epy310
    - codecov

include:
  - template: SAST.gitlab-ci.yml
#  - template: License-Scanning.gitlab-ci.yml
