version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=quips
      - POSTGRES_PASSWORD=quips
    expose:
      - 5432
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    ports:
      - '6379:6379'

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=quips
      - POSTGRES_PASSWORD=quips
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
