[tool.poetry]
name = "quips"
version = "0.1.0"
description = "Silly web app for silly quips."
authors = ["Brad Smith <bradster@infinitewarp.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
Django = "~4.2"
django-environ = "*"
django-model-utils = "*"
django-redis = "*"
gunicorn = "*"
psycopg2-binary = "*"
pytz = "*"
redis = "*"
whitenoise = "*"
djangorestframework = "*"
unidecode = "^1.3.8"

[tool.poetry.group.dev.dependencies]
black = { version = "*", allow-prereleases = true }
django-extensions = "*"
flake8 = "*"
flake8-docstrings = "*"
flake8-import-order = "*"
flake8-black = "*"
faker = "*"
coverage = "*"
werkzeug = "^2.0.0"
tox = "^4.6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
