FROM python:3.13
ENV PYTHONUNBUFFERED 1

RUN pip install poetry

# Install here so packages can be cached ahead of the app itself.
COPY poetry.lock pyproject.toml /
RUN poetry config virtualenvs.create false \
  && poetry install --verbose --no-interaction --no-ansi

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
