# Generated by Django 3.1 on 2020-08-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_auto_20160314_0308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["domain"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
